const translationMap = {
    '`': 'ා	',
    '1': '1',
    '2': '2',
    '3': '3',
    '4': '4',
    '5': '5',
    '6': '6',
    '7': '7',
    '8': '8',
    '9': '9',
    '0': '0',
    '-': '-',
    '=': '=',
    'q': 'ද',
    'w': 'ත',
    'e': 'එ',
    'r': 'ර',
    't': 'ට',
    'y': 'ය',
    'u': 'උ',
    'i': 'ඉ',
    'o': 'ඔ',
    'p': 'ප',
    '[': 'ු',
    ']': 'ි',
    '\\': "්",
    'a': 'අ',
    's': 'ස',
    'd': 'ඩ',
    'f': 'ෆ',
    'g': 'ග',
    'h': 'හ',
    'j': 'ජ',
    'k': 'ක',
    'l': 'ල',
    ';': 'ු',
    '\'': '\'',
    'z': 'ඤ',
    'x': 'භ',
    'c': 'ච',
    'v': 'ව',
    'b': 'බ',
    'n': 'න',
    'm': 'ම',
    ',': ',',
    '.': '.',
    '/': '/',
    '~': '`',
    '!': '!',
    '@': ' ෙ',
    '#': 'ැ',
    '$': 'ෑ',
    '%': '%',
    '^': 'ෘ',
    '&': 'ය',
    '*': 'x',
    '(': '(',
    ')': ')',
    '_': 'ෟ',
    '+': '+',
    'Q': 'ඳ',
    'W': 'ථ',
    'E': 'ධ',
    'R': 'ක්‍ෂ',
    'T': 'ඨ',
    'Y': 'ර',
    'U': 'ළු',
    'I': 'ඊ',
    'O': 'උ',
    'P': 'ඒ',
    '{': 'ූ',
    '}': 'ි',
    '|': 'ි',
    'A': '◌',
    'S': 'ෂ',
    'D': 'ඩ',
    'F': 'ැ',
    'G': 'ඟ',
    'H': 'ෑ',
    'J': 'ඣ',
    'K': 'ඛ',
    'L': 'ළ',
    ':': ':'
};


        function translatetext() {
    const kaputaText = document.getElementById("kaputaInput").value;
    let singlishText = '';

    for (let i = 0; i < kaputaText.length; i++) {
        if (translationMap[kaputaText[i]]) {
            singlishText += translationMap[kaputaText[i]];
        } else {
            singlishText += kaputaText[i];
        }
    }

    document.getElementById("singlishOutput").value = singlishText;
}
